apiVersion: batch/v1
kind: Job
metadata:
  generateName: presync-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: presync
        image: busybox
        command: ["exit",  "1"]
      restartPolicy: Never
  backoffLimit: 4
