---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bgd
  name: bgd
  namespace: bgd
spec:
  ports:
  - name: http-8080 
    port: 8080
    nodePort: 32323
    protocol: TCP
    targetPort: 8080
  selector:
    app: bgd
  type: LoadBalancer
---
